# Игнорируемые правила
ignore = ["E302" ]

# Максимальная длина строки
line-length = 150

# Исключаемые файлы/папки
exclude = [
    ".git",
    "__pycache__",
    "migrations",
    "venv",
    "config",
]
