from service.settings import ENV_APP

CONFIG = ENV_APP['AUTH']

# Настройки JWT

SECRET_KEY = CONFIG["SECRET_KEY"]
ALGORITHM = CONFIG["ALGORITHM_JWT"]
ACCESS_LIFETIME = int(CONFIG['ACCESS_LIFETIME'])
REFRESH_LIFETIME = int(CONFIG['REFRESH_LIFETIME'])
